# Generated by Django 5.0.7 on 2024-08-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bitcoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Year", models.IntegerField()),
                ("Schizophrenia_disorders", models.FloatField(max_length=90)),
                ("Depressive_disorders", models.FloatField(max_length=90)),
                ("Anxiety_disorders", models.FloatField(max_length=90)),
                ("Bipolar_disorders", models.FloatField(max_length=90)),
                ("Eating_disorders", models.FloatField(max_length=90)),
            ],
        ),
    ]
